[env:genericSTM32F103V8]
platform = ststm32
board = genericSTM32F103V8
framework = stm32cube

board_build.f_cpu = 72000000L

upload_protocol = stlink
debug_tool = stlink
monitor_speed = 115200

build_flags =
    -DSTM32F103xB
    -Ilib/fatfs/src
